controllers:
    resource: ../src/Controller/
    type: annotation
    #prefix: /{_locale}
    #requirements:
    #    _locale: '%app_locales%'

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_logout:
    path: /logout
    methods: GET

#homepage:
#    path: /{_locale}
#    requirements:
#        _locale: '%app_locales%'
#        controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
#        defaults:
#            template: default/homepage.html.twig
#            _locale: '%locale%'  

